created navbar
WildCodeSchool/2023-11-php-REM-POEC-FlexiDiary pull request #4
Opened 2023-12-07 16:31 UTC by Chilluno

2023-12-07 16:34 UTC, anjalaN submitted a review, later dismissed

2023-12-08 08:13 UTC, Esoriak approved these changes
It's better to put the html in the Home/index.htm.twig in the componens but we can make this later so i validate

2023-12-08 08:28 UTC, Esoriak requested changes
We"ll create one components for the navbar before the merged

2023-12-08 08:47 UTC, Esoriak approved these changes
components done

2023-12-08 08:49 UTC, anjalaN approved these changes

2023-12-08 08:52 UTC, GuillaumeCregut approved these changes

2023-12-08 08:52 UTC, merged